### ISSUE TITLE
hiding actionbar creates a white space below tabbar

### ISSUE THREAD

**Issue by arpitkh96** [mzgreen/HideOnScrollExample#4]
here is the implementation
https://github.com/arpitkh96/AmazeFileManager/commit/b56934fe56301d203638a8935e0fb5de768f5edd

Screenshots
https://drive.google.com/file/d/0B7y8VGv6MgR5dU5zS1VibEJYMjg/view?usp=sharing
https://drive.google.com/file/d/0B7y8VGv6MgR5TmhiSTVTdG9oSk0/view?usp=sharing

**Comment by mzgreen** [comment]
It seems to me that your padding above the list is bigger than the toolbar's height because you have this path bar below the toolbar. And this path bar's height is greater than toolbar's height. I think that you should modify HidingScrollListener class. There is mToolbarHeight variable, try to set it to your path bar's height instead of toolbar height.

**Comment by arpitkh96** [comment]
That didn't worked. Problem is something different. Related to layout only.

**Comment by arpitkh96** [comment]
One more  strange thing. Headers and dividers of recycler view are visible in that white space but row items arent.

**Comment by arpitkh96** [comment]
Solved... Padding was the problem

**Comment by arpitkh96** [comment]
I added header instead of padding
